preload = ~/Downloads/windows-10-windows-10x-windows-11-minimalism-material-minimal-hd-wallpaper-90904529ef865ed3f8df37d67bb62418.jpg
wallpaper = , ~/Downloads/windows-10-windows-10x-windows-11-minimalism-material-minimal-hd-wallpaper-90904529ef865ed3f8df37d67bb62418.jpg
